language: python
matrix:
  include:
    - python: "2.7"
    - pytest

virtualenv:
  system_site_packages: true

install:
  - pip install SpiNNMachine --user
  - curl --silent --location https://raw.github.com/clear-code/cutter/master/data/travis/setup.sh | sh

before_script:
  - python ./setup.py install
script: "cd unittests && py.test *.py && cd ../integration_tests && py.test . && cd ../c_data_specification && make && make check"
